# Basic
title: 黄sir
subtitle: 个人站
description: This is my home field
# 头像里面的标题
avatarTitle: Nice
# 头像里面的描述
avatarDesc: 分享美文!!!
url: "http://i3.sinaimg.cn/ent/2013/0625/U3349P28DT20130625181913.jpg"

# Comment
comment:
    disqus: leopard
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    weibo: 1242189726
    github: hzx0406
    # twitter: 
    mail: leopardpan@icloud.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: UA-84134159-3   
    host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


